### ISSUE TITLE
关于 worker 运行 service role 权限不足整体流程异常的问题

### ISSUE THREAD

**Issue by wss-git** [serverless-cd/serverless-cd#48]
![image](https://user-images.githubusercontent.com/56686088/229458379-a605abc5-228b-445d-885b-3c0b1898a966.png)

原因 授权账户缺少一些 fc 相关的权限导致的

**Comment by wss-git** [comment]
解决方式：role 可以尝试使用 [yaml 声明](https://docs.serverless-devs.com/fc/yaml/service#role)的方式。这种方式之前是可以，已经好多年没有使用了 不知道还支不支持

**Comment by heimanba** [comment]
是否可以通过文档提示来解决，部署之前告知需要的权限

**Comment by wss-git** [comment]
```
role:
  name: roleName
  policies:
      - AliyunFCDefaultRolePolicy
      - AliyunFCFullAccess
```
