### ISSUE TITLE
【04121】体验问题收敛 

### ISSUE THREAD

**Issue by heimanba** [serverless-cd/serverless-cd#63]
- [x] 【BUG】同一个仓库同时在两个团队导入问题

![image](https://user-images.githubusercontent.com/5129967/233409541-358c0235-9522-4aa1-ac7b-e79d39de08a2.png)

**Comment by heimanba** [comment]
YAML 格式不准确，导致Engine挂掉。
这些日志应该能被 Logger接收。 @xsahxl 


![image](https://user-images.githubusercontent.com/5129967/233410869-3eb3ef67-0eb1-429f-93f4-756c9d69b841.png)


```
name: Deploy Express application to FC
steps:
   - plugin: "@serverless-cd/cache"
    id: my-cache
    inputs:
      key: 'test-1'
      path: ~/.npm
      region: cn-qingdao
      ossConfig:
        bucket: serverless-cd-qingdao
        internal: false
      credentials:
        accessKeySecret: ${{cloudSecrets.AccessKeySecret}}
        accessKeyID: ${{cloudSecrets.AccessKeyID}}
  - run: npm i @serverless-devs/s -g --registry=https://registry.npmmirror.com
  - run: s -v
  - run: >-
      s config add  --AccessKeyID ${{cloudSecrets.AccessKeyID}}  --AccessKeySecret
      ${{cloudSecrets.AccessKeySecret}} -a default -f
  - run: s deploy --use-local -y

```
